# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vandalsquat_development
  host: localhost
  port: 5432
  username: postgres
  password: postgres

test:
  <<: *default
  database: vandalsquat_test
  host: localhost
  port: 5432
  username: postgres
  password: postgres

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  sslmode: require  # ADD THIS LINE